mqtt:
  host: "${MQTT_HOST}"
  port: ${MQTT_PORT}
  username: "${MQTT_USERNAME}"
  password: "${MQTT_PASSWORD}"
rest:
  base_url: ${VO_URL}/api/clients
publish:
# Depth
- rest_endpoint: /D001/3319/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3319/0
  mid: DepthState
  polling_interval: 10
  body:
    value: "<placeholder>"
# Gain
- rest_endpoint: /D001/33320/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: "${ID_DEVICE}/REMOTECLIENT_ROUTING_KEY"
  mid: GainState
  polling_interval: 10
  body:
    value: "<placeholder>"
# Width
- rest_endpoint: /D001/33321/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: "${ID_DEVICE}/REMOTECLIENT_ROUTING_KEY"
  mid: WidthState
  polling_interval: 10
  body:
    value: "<placeholder>"
# Scan correlation
- rest_endpoint: /D001/33322/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: "${ID_DEVICE}/REMOTECLIENT_ROUTING_KEY"
  mid: ScanCorrelationState
  polling_interval: 10
  body:
    value: "<placeholder>"
cmds:
  DepthCommand: 3319
  GainCommand: 33320
  WidthCommand: 33321
  ScanCommand: 33322
subscribe:
- mqtt_topic: "${ID_DEVICE}/REMOTECLIENT_ROUTING_KEY"
  rest_endpoint: /D001/${VO_CMD}/0/5700
  rest_method: PUT
  body:
    id: 5700
    value: "<placeholder>"
