mqtt:
  host: localhost
  port: 1883
rest:
  base_url: http://127.0.0.1:8000
publish:
- rest_endpoint: books/
  rest_method: GET
  mqtt_topic: books
  polling_interval: 10
  headers:
    Content-Type: "application/json"
subscribe:
- mqtt_topic: books
  rest_endpoint: books/
  rest_method: POST
  headers:
    Content-Type: "application/json"
