http:
  base_url: "YOUR_HTTP_API_BASE_URL"  # Replace with your API base URL
  endpoint: "/your/api/endpoint"  # Replace with the specific endpoint
  headersS: {"Content-Type": "application/json"}  # Example headers
mqtt:
  broker_address: "YOUR_MQTT_BROKER_ADDRESS"  # Replace with your broker address
  broker_port: 1883  # Default MQTT port
  username: "YOUR_MQTT_USERNAME"  # Optional
  password: "YOUR_MQTT_PASSWORD"  # Optional
  topic_publish: "your/publish/topic"  # Replace with your publish topic
  topic_subscribe: "your/subscribe/topic"  # Replace with your subscribe topic
