mqtt:
  host: localhost
  port: 1883
rest:
  base_url: http://127.0.0.1:5555/api/clients
publish:
# Depth
- rest_endpoint: /D001/3319/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3319/0
  polling_interval: 10
  body:
    tmstp: ""
    e:
      - v: $value
# Gain
- rest_endpoint: /D001/33320/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3320/0
  polling_interval: 10
  body:
    tmstp: ""
    e:
      - v: $value
# Width
- rest_endpoint: /D001/33321/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3321/0
  polling_interval: 10
  body:
    tmstp: ""
    e:
      - v: $value
# Scan correlation
- rest_endpoint: /D001/33322/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3322/0
  polling_interval: 10
  body:
      tmstp: ""
      e:
        - v: $value
subscribe:
# Depth
- mqtt_topic: cmnd/D001/3319/0
  rest_endpoint: /D001/3319/0/5700
  rest_method: PUT
  body:
    id: 5700
    value: $value
# Gain
- mqtt_topic: cmnd/D001/3320/0
  rest_endpoint: /D001/33320/0/5700
  rest_method: PUT\
  body:
    id: 5700
    value: $value
# Width
- mqtt_topic: cmnd/D001/3321/0
  rest_endpoint: /D001/33321/0/5700
  rest_method: PUT
  body:
    id: 5700
    value: $value
# Scan correlation
- mqtt_topic: cmnd/D001/3322/0
  rest_endpoint: /DD1/33322/0/5700
  rest_method: PUT
  body:
    id: 5700
    value: $value
