mqtt:
  host: "${MQTT_HOST}"
  port: ${MQTT_PORT}
  username: "${MQTT_USERNAME}"
  password: "${MQTT_PASSWORD}"
rest:
  base_url: ${VO_URL}/api/clients
publish:
# Depth
- rest_endpoint: /D001/3319/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3319/0
  polling_interval: 10
  body:
    tmstp: ""
    e:
      - v: "<placeholder>"
# Gain
- rest_endpoint: /D001/33320/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3320/0
  polling_interval: 10
  body:
    tmstp: ""
    e:
      - v: "<placeholder>"
# Width
- rest_endpoint: /D001/33321/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3321/0
  polling_interval: 10
  body:
    tmstp: ""
    e:
      - v: "<placeholder>"
# Scan correlation
- rest_endpoint: /D001/33322/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3322/0
  polling_interval: 10
  body:
      tmstp: ""
      e:
        - v: "<placeholder>"
subscribe:
# Depth
- mqtt_topic: cmnd/D001/3319/0
  rest_endpoint: /D001/3319/0/5700
  rest_method: PUT
  body:
    id: 5700
    value: "<placeholder>"
# Gain
- mqtt_topic: cmnd/D001/3320/0
  rest_endpoint: /D001/33320/0/5700
  rest_method: PUT\
  body:
    id: 5700
    value: "<placeholder>"
# Width
- mqtt_topic: cmnd/D001/3321/0
  rest_endpoint: /D001/33321/0/5700
  rest_method: PUT
  body:
    id: 5700
    value: "<placeholder>"
# Scan correlation
- mqtt_topic: cmnd/D001/3322/0
  rest_endpoint: /DD1/33322/0/5700
  rest_method: PUT
  body:
    id: 5700
    value: "<placeholder>"
