mqtt:
  host: "${MQTT_HOST}"
  port: ${MQTT_PORT}
  username: "${MQTT_USERNAME}"
  password: "${MQTT_PASSWORD}"
rest:
  base_url: ${VO_URL}/api/clients
publish:
# Depth
- rest_endpoint: /D001/3319/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: stat/D001/3319/0
  message_id: DepthState
  polling_interval: 10
  body:
    Value: "<VALUE>"
# Gain
- rest_endpoint: /D001/33320/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: "${ID_DEVICE}/REMOTECLIENT_ROUTING_KEY"
  message_id: GainState
  polling_interval: 10
  body:
    Value: "<VALUE>"
# Width
- rest_endpoint: /D001/33321/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: "${ID_DEVICE}/REMOTECLIENT_ROUTING_KEY"
  message_id: WidthState
  polling_interval: 10
  body:
    Value: "<VALUE>"
# Scan correlation
- rest_endpoint: /D001/33322/0/5700?getRealtime=true
  rest_method: GET
  mqtt_topic: "${ID_DEVICE}/REMOTECLIENT_ROUTING_KEY"
  message_id: ScanCorrelationState
  polling_interval: 10
  body:
    Status: "<VALUE>"
cmd:
  DepthCommand: 3316
  GainCommand: 33320
  WidthCommand: 33321
  ScanCommand: 33322
subscribe:
- mqtt_topic: "${ID_DEVICE}/REMOTECLIENT_ROUTING_KEY"
  rest_endpoint: /D001/<VO_CMD>/0/5700
  rest_method: PUT
  body:
    id: 5700
    value: "<VALUE>"
